spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Code9017!!
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200
    refreshTokenExpiration: 604800
stripe:
  secretKey:${STRIPE_SECRET_KEY}
  webhookKey:${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost/8080

